// <auto-generated />
using JurassicPark.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JurassicPark.Migrations
{
    [DbContext(typeof(JurassicParkContext))]
    [Migration("20210610010641_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("JurassicPark.Models.Dinosaur", b =>
                {
                    b.Property<int>("DinosaurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DinosaurId");

                    b.ToTable("Dinosaurs");

                    b.HasData(
                        new
                        {
                            DinosaurId = 1,
                            Age = 7,
                            Gender = "Female",
                            Name = "Matilda",
                            Species = "Dinosaur"
                        },
                        new
                        {
                            DinosaurId = 2,
                            Age = 10,
                            Gender = "Female",
                            Name = "Rex",
                            Species = "Dinosaur"
                        },
                        new
                        {
                            DinosaurId = 3,
                            Age = 2,
                            Gender = "Female",
                            Name = "Trey Ceratops"
                        },
                        new
                        {
                            DinosaurId = 4,
                            Age = 4,
                            Gender = "Male",
                            Name = "Pip",
                            Species = "Dinosaur"
                        },
                        new
                        {
                            DinosaurId = 5,
                            Age = 22,
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
